// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_name_ from "./routes/[name].tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $blog_slug_ from "./routes/blog/[slug].tsx";
import * as $index from "./routes/index.tsx";
import * as $User from "./islands/User.tsx";
import * as $Wish from "./islands/Wish.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[name].tsx": $_name_,
    "./routes/_404.tsx": $_404,
    "./routes/blog/[slug].tsx": $blog_slug_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/User.tsx": $User,
    "./islands/Wish.tsx": $Wish,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
